Отрисовка тестовых данных
htmlacademy-javascript/1360725-kekstagram-23 pull request #5
Opened 2021-07-04 20:12 UTC by E1ect96

2021-07-04 21:23 UTC, ademaro commented on js/render-thumbnails.js
> +import {getPhotos} from'/js/data.js';
`import {getPhotos} from'./data.js';`

2021-07-04 21:25 UTC, ademaro commented on js/main.js
> -getPhotos(25);
нет, тут как раз тебе надо сгенерировать данные, сохранить в переменную и потом эти данные передать ф-ции отрисовке, примерно так должно получится:
```js
photosData = getPhotos(NUMBER_OF_PHOTOS);
renderThumbnails(photosData);
```

2021-07-04 21:26 UTC, ademaro commented on js/render-thumbnails.js
> +  getPhotos(amount).forEach(({url, comments, likes}) => {
деструктуризация — круто! Вот только тут надо итерироваться по тем фоткам, которые надо передать через параметр

2021-07-04 21:26 UTC, E1ect96 commented on js/main.js
> -getPhotos(25);
приступив ко второй части первым делом вынес создание временных данных в main

2021-07-04 21:27 UTC, ademaro requested changes
Давай чутка поправим, что бы двинуть дальше + пора бы почистить проверки

2021-07-05 10:34 UTC, ademaro commented on js/render-thumbnails.js
> +const renderThumbnails = function (data) {
data -> picturesData, например

2021-07-05 10:34 UTC, merged